import CardGlobalProviders from "@/app/(client)/providers";
import Navbar from "@/app/_components/navbar";
import Sidebar from "@/app/_components/sidebar";
import Providers from "@/app/providers";
import { EditProfileSheet } from "@/components/ui/edit-profile-sheet";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import React from "react";
import "../../../globals.css";

export const metadata: Metadata = {
  title: " ",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html>
      <body>
        <div className="flex h-screen">
    

          <div className="inline-block">
            <Sidebar />
          </div>
          <CardGlobalProviders>
            <Providers>
              <div className="flex  w-full flex-col">
                {/* Navbar */}
                <Navbar />
                <main className="relative w-full overflow-x-hidden overflow-y-auto p-2">
                  {children}
                </main>
                <EditProfileSheet/>
                <Toaster />
              </div>
            </Providers>
          </CardGlobalProviders>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
