import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Providers from '../providers'
import LandPageNavBar from '../_components/_LandingPageComponents/LandPageNavBar'
import Footer from '../_components/Footer'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <LandPageNavBar />
        <Providers>{children}</Providers>
        <Footer />
        <Toaster />
      </body>
    </html>
  )
}
