import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Providers from "../providers";
import LandPageNavBar from "../_components/_LandingPageComponents/LandPageNavBar";
import Footer from "../_components/Footer";
import { Toaster } from "@/components/ui/toaster";
import { CardProvider } from "../../../context/CardContext";
import CardGlobalProviders from "./providers";
import { EditProfileSheet } from "@/components/ui/edit-profile-sheet";
import { CardList } from "./products/components/card-list";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CardGlobalProviders>
          <Providers>
            <LandPageNavBar />
            {children}
            <Toaster />
            <EditProfileSheet/>
            <CardList/>
          </Providers>
          <Footer />
        </CardGlobalProviders>
      </body>
    </html>
  );
}
